// GENERATED by tools/gen_start_slots.py -- do not edit.
//
// Explicit start slots for players 6-11 on the shipped playfields: one entry per map and slot
// set (race grid; battle ring for Tag and Survival; Capture the Flag, even players red, odd
// green). Each entry is keyed by the map size and the exact authored MyStartCoord items for
// players 0-5 of its set, so StartSlots_Fill (StartSlots.c) falls back to the procedural rule
// on modified maps. Coordinates are world units (gPlayerInfo startX/startZ); headings are 1/16
// turns, like MyStartCoord parm[1]. The comments say how each slot was placed.
//
// Regenerate: python3 tools/gen_start_slots.py
// Verify:     python3 tools/gen_start_slots.py --check

#include "startslots.h"

const StartSlotTableEntry kStartSlotTable[] =
{
	{
		.map = "StoneAge_Desert", .set = START_SLOT_SET_RACE,
		.mapUnitWidth = 140800, .mapUnitDepth = 128000,
		.authored =
		{
			{ 73500,  88300, 12 },	// p0
			{ 74600,  87350, 12 },	// p1
			{ 74500,  89250, 12 },	// p2
			{ 74400,  88400, 12 },	// p3
			{ 75550,  87450, 12 },	// p4
			{ 75450,  88850, 12 },	// p5
		},
		.extra =
		{
			{ 70150,  87105, 12 },	// p6: rule wave 1200 left, lanes x1.15
			{ 71250,  86013, 12 },	// p7: rule wave 1200 left, lanes x1.15
			{ 71150,  88198, 12 },	// p8: rule wave 1200 left, lanes x1.15
			{ 71050,  87220, 12 },	// p9: rule wave 1200 left, lanes x1.15
			{ 72200,  86128, 12 },	// p10: rule wave 1200 left, lanes x1.15
			{ 72100,  87738, 12 },	// p11: rule wave 1200 left, lanes x1.15
		},
	},
	{
		.map = "StoneAge_Jungle", .set = START_SLOT_SET_RACE,
		.mapUnitWidth = 128000, .mapUnitDepth = 128000,
		.authored =
		{
			{ 85500,  97300,  8 },	// p0
			{ 85650,  98550,  8 },	// p1
			{ 86700,  98500,  8 },	// p2
			{ 86700,  97150,  8 },	// p3
			{ 86900,  99950,  8 },	// p4
			{ 85750,  99950,  8 },	// p5
		},
		.extra =
		{
			{ 85300,  93200,  8 },	// p6: rule wave 200 right
			{ 85450,  94450,  8 },	// p7: rule wave 200 right
			{ 86500,  94400,  8 },	// p8: rule wave 200 right
			{ 86500,  93050,  8 },	// p9: rule wave 200 right
			{ 86700,  95850,  8 },	// p10: rule wave 200 right
			{ 85550,  95850,  8 },	// p11: rule wave 200 right
		},
	},
	{
		.map = "StoneAge_Ice", .set = START_SLOT_SET_RACE,
		.mapUnitWidth = 160000, .mapUnitDepth = 160000,
		.authored =
		{
			{ 58450, 129050, 12 },	// p0
			{ 58550, 130450, 12 },	// p1
			{ 59700, 129100, 12 },	// p2
			{ 59850, 130500, 12 },	// p3
			{ 61050, 129050, 12 },	// p4
			{ 61200, 130550, 12 },	// p5
		},
		.extra =
		{
			{ 54400, 129050, 12 },	// p6: rule
			{ 54500, 130450, 12 },	// p7: rule
			{ 55650, 129100, 12 },	// p8: rule
			{ 55800, 130500, 12 },	// p9: rule
			{ 57000, 129050, 12 },	// p10: rule
			{ 57150, 130550, 12 },	// p11: rule
		},
	},
	{
		.map = "BronzeAge_Crete", .set = START_SLOT_SET_RACE,
		.mapUnitWidth = 128000, .mapUnitDepth = 128000,
		.authored =
		{
			{ 11300,  67350,  8 },	// p0
			{ 10200,  68550,  8 },	// p1
			{ 12500,  67350,  8 },	// p2
			{ 12500,  68550,  8 },	// p3
			{ 11400,  68600,  8 },	// p4
			{ 10150,  67350,  8 },	// p5
		},
		.extra =
		{
			{ 11300,  64800,  8 },	// p6: rule
			{ 10200,  66000,  8 },	// p7: rule
			{ 12500,  64800,  8 },	// p8: rule
			{ 12500,  66000,  8 },	// p9: rule
			{ 11400,  66050,  8 },	// p10: rule
			{ 10150,  64800,  8 },	// p11: rule
		},
	},
	{
		.map = "BronzeAge_China", .set = START_SLOT_SET_RACE,
		.mapUnitWidth = 102400, .mapUnitDepth = 115200,
		.authored =
		{
			{ 18750,  70450,  0 },	// p0
			{ 18750,  69350,  0 },	// p1
			{ 19950,  69350,  0 },	// p2
			{ 19950,  70450,  0 },	// p3
			{ 18750,  68250,  0 },	// p4
			{ 19950,  68200,  0 },	// p5
		},
		.extra =
		{
			{ 23150,  74000,  0 },	// p6: rule wave 4400 right
			{ 23150,  72900,  0 },	// p7: rule wave 4400 right
			{ 24350,  72900,  0 },	// p8: rule wave 4400 right
			{ 24350,  74000,  0 },	// p9: rule wave 4400 right
			{ 23150,  71800,  0 },	// p10: rule wave 4400 right
			{ 24350,  71750,  0 },	// p11: rule wave 4400 right
		},
	},
	{
		.map = "BronzeAge_Egypt", .set = START_SLOT_SET_RACE,
		.mapUnitWidth = 134400, .mapUnitDepth = 128000,
		.authored =
		{
			{116250,  74350,  0 },	// p0
			{117500,  74400,  0 },	// p1
			{116100,  73050,  0 },	// p2
			{117400,  73100,  0 },	// p3
			{115950,  71850,  0 },	// p4
			{117000,  71700,  0 },	// p5
		},
		.extra =
		{
			{118050,  78350,  0 },	// p6: rule wave 1800 right
			{119300,  78400,  0 },	// p7: rule wave 1800 right
			{117900,  77050,  0 },	// p8: rule wave 1800 right
			{119200,  77100,  0 },	// p9: rule wave 1800 right
			{117750,  75850,  0 },	// p10: rule wave 1800 right
			{118800,  75700,  0 },	// p11: rule wave 1800 right
		},
	},
	{
		.map = "IronAge_Europe", .set = START_SLOT_SET_RACE,
		.mapUnitWidth = 166400, .mapUnitDepth = 166400,
		.authored =
		{
			{129000, 141250,  0 },	// p0
			{130250, 141250,  0 },	// p1
			{128950, 139950,  0 },	// p2
			{130250, 139950,  0 },	// p3
			{129000, 138700,  0 },	// p4
			{130250, 138700,  0 },	// p5
		},
		.extra =
		{
			{129100, 145100,  0 },	// p6: rule wave 100 right
			{130350, 145100,  0 },	// p7: rule wave 100 right
			{129050, 143800,  0 },	// p8: rule wave 100 right
			{130350, 143800,  0 },	// p9: rule wave 100 right
			{129100, 142550,  0 },	// p10: rule wave 100 right
			{130350, 142550,  0 },	// p11: rule wave 100 right
		},
	},
	{
		.map = "IronAge_Scandinavia", .set = START_SLOT_SET_RACE,
		.mapUnitWidth = 128000, .mapUnitDepth = 128000,
		.authored =
		{
			{ 82950,  23300,  3 },	// p0
			{ 82850,  24600,  3 },	// p1
			{ 81500,  23400,  3 },	// p2
			{ 81450,  24650,  3 },	// p3
			{ 80100,  23400,  3 },	// p4
			{ 80100,  24750,  3 },	// p5
		},
		.extra =
		{
			{ 87267,  24114,  3 },	// p6: rule wave 900 right
			{ 87167,  25414,  3 },	// p7: rule wave 900 right
			{ 85817,  24214,  3 },	// p8: rule wave 900 right
			{ 85767,  25464,  3 },	// p9: rule wave 900 right
			{ 84417,  24214,  3 },	// p10: rule wave 900 right
			{ 84417,  25564,  3 },	// p11: rule wave 900 right
		},
	},
	{
		.map = "IronAge_Atlantis", .set = START_SLOT_SET_RACE,
		.mapUnitWidth = 115200, .mapUnitDepth = 115200,
		.authored =
		{
			{ 74200, 107750, 13 },	// p0
			{ 76500, 108950, 13 },	// p1
			{ 76550, 107800, 13 },	// p2
			{ 75350, 108900, 13 },	// p3
			{ 74200, 109000, 13 },	// p4
			{ 75350, 107750, 13 },	// p5
		},
		.extra =
		{
			{ 70569, 109254, 13 },	// p6: rule
			{ 72869, 110454, 13 },	// p7: rule
			{ 72919, 109304, 13 },	// p8: rule
			{ 71719, 110404, 13 },	// p9: rule
			{ 70569, 110504, 13 },	// p10: rule
			{ 71719, 109254, 13 },	// p11: rule
		},
	},
	{
		.map = "Battle_StoneHenge", .set = START_SLOT_SET_BATTLE,
		.mapUnitWidth = 57600, .mapUnitDepth = 51200,
		.authored =
		{
			{ 30450,  23450,  8 },	// p0
			{ 30300,  25000, 10 },	// p1
			{ 33350,  25150,  2 },	// p2
			{ 33600,  23550,  4 },	// p3
			{ 31900,  26450,  0 },	// p4
			{ 31950,  22450,  6 },	// p5
		},
		.extra =
		{
			{ 28902,  24280, 12 },	// p6: rule
			{ 30047,  26749, 14 },	// p7: rule
			{ 34863,  24319,  4 },	// p8: rule
			{ 33719,  21749,  6 },	// p9: rule
			{ 33594,  27313,  1 },	// p10: rule
			{ 30365,  21556,  9 },	// p11: rule
		},
	},
	{
		.map = "Battle_StoneHenge", .set = START_SLOT_SET_CTF,
		.mapUnitWidth = 57600, .mapUnitDepth = 51200,
		.authored =
		{
			{ 45200,  34900,  2 },	// p0
			{ 20450,  11050,  7 },	// p1
			{ 44150,  36300,  2 },	// p2
			{ 21800,  10400,  7 },	// p3
			{ 44050,  34950,  2 },	// p4
			{ 21750,  11750,  7 },	// p5
		},
		.extra =
		{
			{ 42900,  35300,  2 },	// p6: moved 996 from the rule
			{ 22800,  11100,  7 },	// p7: moved 1000 from the rule
			{ 42800,  36400,  2 },	// p8: rule
			{ 23300,  10000,  7 },	// p9: moved 474 from the rule
			{ 41800,  34800,  2 },	// p10: moved 934 from the rule
			{ 23200,  12200,  7 },	// p11: moved 412 from the rule
		},
	},
	{
		.map = "Battle_Aztec", .set = START_SLOT_SET_BATTLE,
		.mapUnitWidth = 57600, .mapUnitDepth = 51200,
		.authored =
		{
			{ 32950,  10900,  6 },	// p0
			{ 29900,  11600,  6 },	// p1
			{ 29650,   8350,  6 },	// p2
			{ 30800,   9900,  6 },	// p3
			{ 28050,   9900,  6 },	// p4
			{ 32900,   8950,  6 },	// p5
		},
		.extra =
		{
			{ 34300,   9100,  5 },	// p6: moved 416 from the rule
			{ 30935,  13077,  0 },	// p7: rule
			{ 27834,   8516, 11 },	// p8: rule
			{ 31606,   8863,  6 },	// p9: rule
			{ 27255,  11869, 13 },	// p10: rule
			{ 32875,   6931,  6 },	// p11: rule
		},
	},
	{
		.map = "Battle_Aztec", .set = START_SLOT_SET_CTF,
		.mapUnitWidth = 57600, .mapUnitDepth = 51200,
		.authored =
		{
			{ 20900,  15150,  8 },	// p0
			{ 40650,  30400,  1 },	// p1
			{ 22000,  14150,  8 },	// p2
			{ 38550,  32450,  1 },	// p3
			{ 23250,  13400,  8 },	// p4
			{ 39550,  31350,  1 },	// p5
		},
		.extra =
		{
			{ 21650,  16400,  8 },	// p6: rule
			{ 39700,  29500,  1 },	// p7: moved 180 from the rule
			{ 22750,  15400,  8 },	// p8: rule
			{ 37450,  31450,  1 },	// p9: rule
			{ 24000,  14500,  8 },	// p10: moved 150 from the rule
			{ 38450,  30350,  1 },	// p11: rule
		},
	},
	{
		.map = "Battle_Coliseum", .set = START_SLOT_SET_BATTLE,
		.mapUnitWidth = 51200, .mapUnitDepth = 44800,
		.authored =
		{
			{ 33650,  25000,  6 },	// p0
			{ 33700,  26150,  2 },	// p1
			{ 32150,  27250,  0 },	// p2
			{ 32300,  23750,  8 },	// p3
			{ 30650,  26450, 14 },	// p4
			{ 30650,  24900, 10 },	// p5
		},
		.extra =
		{
			{ 33967,  23324,  6 },	// p6: rule
			{ 35062,  25100,  4 },	// p7: rule
			{ 33615,  28181,  1 },	// p8: rule
			{ 30790,  22772,  9 },	// p9: rule
			{ 30628,  28220, 15 },	// p10: rule
			{ 29220,  25893, 12 },	// p11: rule
		},
	},
	{
		.map = "Battle_Coliseum", .set = START_SLOT_SET_CTF,
		.mapUnitWidth = 51200, .mapUnitDepth = 44800,
		.authored =
		{
			{ 21800,  23600, 12 },	// p0
			{ 43600,  24450,  4 },	// p1
			{ 21900,  25400, 12 },	// p2
			{ 43650,  25950,  4 },	// p3
			{ 21900,  27200, 12 },	// p4
			{ 43650,  27300,  4 },	// p5
		},
		.extra =
		{
			{ 23600,  23600, 12 },	// p6: rule
			{ 42250,  24450,  4 },	// p7: rule
			{ 23700,  25400, 12 },	// p8: rule
			{ 42300,  25950,  4 },	// p9: rule
			{ 23700,  27200, 12 },	// p10: rule
			{ 42300,  27300,  4 },	// p11: rule
		},
	},
	{
		.map = "Battle_Maze", .set = START_SLOT_SET_BATTLE,
		.mapUnitWidth = 57600, .mapUnitDepth = 51200,
		.authored =
		{
			{ 31950,  22050,  3 },	// p0
			{ 29300,  18150,  6 },	// p1
			{ 25150,  20250,  9 },	// p2
			{ 27500,  18150,  6 },	// p3
			{ 25100,  21900,  9 },	// p4
			{ 32100,  20650,  3 },	// p5
		},
		.extra =
		{
			{ 33718,  20048,  4 },	// p6: rule
			{ 27970,  16747,  8 },	// p7: rule
			{ 24515,  22594, 13 },	// p8: rule
			{ 26300,  19600, 11 },	// p9: moved 1585 from the rule
			{ 25800,  23000, 14 },	// p10: moved 1467 from the rule
			{ 31300,  19700,  4 },	// p11: moved 2242 from the rule
		},
	},
	{
		.map = "Battle_Maze", .set = START_SLOT_SET_CTF,
		.mapUnitWidth = 57600, .mapUnitDepth = 51200,
		.authored =
		{
			{ 17100,  40550,  6 },	// p0
			{ 42900,  17900,  0 },	// p1
			{ 18450,  40500,  6 },	// p2
			{ 44450,  17850,  0 },	// p3
			{ 17700,  42050,  6 },	// p4
			{ 43550,  16350,  0 },	// p5
		},
		.extra =
		{
			{ 18900,  41600,  6 },	// p6: moved 390 from the rule
			{ 43300,  19100,  0 },	// p7: moved 1923 from the rule
			{ 19600,  39900,  6 },	// p8: moved 1408 from the rule
			{ 44500,  19100,  0 },	// p9: moved 1589 from the rule
			{ 19250,  42800,  6 },	// p10: rule
			{ 42800,  16900,  0 },	// p11: moved 827 from the rule
		},
	},
	{
		.map = "Battle_Celtic", .set = START_SLOT_SET_BATTLE,
		.mapUnitWidth = 57600, .mapUnitDepth = 51200,
		.authored =
		{
			{ 32400,  25850,  1 },	// p0
			{ 32400,  24150,  4 },	// p1
			{ 31050,  26650,  0 },	// p2
			{ 30900,  23350,  6 },	// p3
			{ 29350,  25600, 10 },	// p4
			{ 29300,  24250,  7 },	// p5
		},
		.extra =
		{
			{ 33936,  24988,  4 },	// p6: rule
			{ 32459,  22398,  7 },	// p7: rule
			{ 32615,  27413,  2 },	// p8: rule
			{ 29437,  22441,  9 },	// p9: rule
			{ 29069,  27315, 14 },	// p10: rule
			{ 27858,  25274, 12 },	// p11: rule
		},
	},
	{
		.map = "Battle_Celtic", .set = START_SLOT_SET_CTF,
		.mapUnitWidth = 57600, .mapUnitDepth = 51200,
		.authored =
		{
			{ 15900,   3700,  8 },	// p0
			{ 48300,  46950,  1 },	// p1
			{ 15450,   2150,  8 },	// p2
			{ 47200,  48600,  1 },	// p3
			{ 14300,   3500,  8 },	// p4
			{ 46450,  47000,  1 },	// p5
		},
		.extra =
		{
			{ 17250,   4850,  8 },	// p6: rule
			{ 46600,  47900,  1 },	// p7: moved 223 from the rule
			{ 16800,   3300,  8 },	// p8: rule
			{ 45600,  49350,  1 },	// p9: rule
			{ 15650,   4650,  8 },	// p10: rule
			{ 44850,  47750,  1 },	// p11: rule
		},
	},
	{
		.map = "Battle_TarPits", .set = START_SLOT_SET_BATTLE,
		.mapUnitWidth = 57600, .mapUnitDepth = 51200,
		.authored =
		{
			{ 30250,  24600,  9 },	// p0
			{ 30050,  27350, 14 },	// p1
			{ 31700,  27500,  1 },	// p2
			{ 32500,  25950,  4 },	// p3
			{ 29450,  26000, 12 },	// p4
			{ 32000,  24600,  7 },	// p5
		},
		.extra =
		{
			{ 29300,  23800, 10 },	// p6: moved 1005 from the rule
			{ 30740,  28935,  0 },	// p7: rule
			{ 33200,  27200,  3 },	// p8: moved 533 from the rule
			{ 33376,  24515,  5 },	// p9: rule
			{ 29200,  28900, 15 },	// p10: moved 1624 from the rule
			{ 31295,  22989,  8 },	// p11: rule
		},
	},
	{
		.map = "Battle_TarPits", .set = START_SLOT_SET_CTF,
		.mapUnitWidth = 57600, .mapUnitDepth = 51200,
		.authored =
		{
			{ 13800,  11250, 10 },	// p0
			{ 44700,  42400,  2 },	// p1
			{ 13600,   9700, 10 },	// p2
			{ 43900,  43400,  2 },	// p3
			{ 12400,  10700, 10 },	// p4
			{ 43150,  44250,  2 },	// p5
		},
		.extra =
		{
			{ 14800,  12450, 10 },	// p6: rule
			{ 43400,  42300,  2 },	// p7: moved 790 from the rule
			{ 14900,  10900, 10 },	// p8: moved 300 from the rule
			{ 42800,  43100,  2 },	// p9: moved 514 from the rule
			{ 14700,  13700, 10 },	// p10: moved 2220 from the rule
			{ 42500,  41500,  2 },	// p11: moved 2009 from the rule
		},
	},
	{
		.map = "Battle_Spiral", .set = START_SLOT_SET_BATTLE,
		.mapUnitWidth = 57600, .mapUnitDepth = 51200,
		.authored =
		{
			{ 28700,  24250,  2 },	// p0
			{ 27600,  21900,  8 },	// p1
			{ 27700,  25450,  0 },	// p2
			{ 26500,  22900,  8 },	// p3
			{ 26700,  24250, 14 },	// p4
			{ 28850,  23050,  6 },	// p5
		},
		.extra =
		{
			{ 30100,  23900,  4 },	// p6: moved 232 from the rule
			{ 27700,  23100,  7 },	// p7: moved 2616 from the rule, turned -1/16 for a clear run
			{ 29270,  26310,  1 },	// p8: rule
			{ 26700,  25500, 15 },	// p9: moved 2599 from the rule
			{ 27400,  26600,  0 },	// p10: moved 1174 from the rule
			{ 29200,  22000,  6 },	// p11: moved 548 from the rule
		},
	},
	{
		.map = "Battle_Spiral", .set = START_SLOT_SET_CTF,
		.mapUnitWidth = 57600, .mapUnitDepth = 51200,
		.authored =
		{
			{ 53200,  13600,  8 },	// p0
			{ 48800,  13250,  8 },	// p1
			{ 54100,  13650,  8 },	// p2
			{ 47500,  13250,  8 },	// p3
			{ 51950,  13600,  8 },	// p4
			{ 50050,  13250,  8 },	// p5
		},
		.extra =
		{
			{ 53250,  11450,  8 },	// p6: rule
			{ 48800,  16300,  8 },	// p7: moved 500 from the rule
			{ 54200,  12100,  8 },	// p8: moved 602 from the rule
			{ 47500,  15800,  8 },	// p9: rule
			{ 52000,  11450,  8 },	// p10: rule
			{ 50050,  15800,  8 },	// p11: rule
		},
	},
	{
		.map = "Battle_Ramps", .set = START_SLOT_SET_BATTLE,
		.mapUnitWidth = 57600, .mapUnitDepth = 51200,
		.authored =
		{
			{ 31550,  24300,  6 },	// p0
			{ 30300,  26350,  0 },	// p1
			{ 29400,  24050, 10 },	// p2
			{ 30600,  23300,  8 },	// p3
			{ 29250,  25350, 14 },	// p4
			{ 31700,  25350,  2 },	// p5
		},
		.extra =
		{
			{ 31926,  22770,  6 },	// p6: rule
			{ 31632,  27411,  1 },	// p7: rule
			{ 27880,  24579, 12 },	// p8: rule
			{ 29293,  22252,  9 },	// p9: rule
			{ 28950,  26946, 14 },	// p10: rule
			{ 33112,  24536,  4 },	// p11: rule
		},
	},
	{
		.map = "Battle_Ramps", .set = START_SLOT_SET_CTF,
		.mapUnitWidth = 57600, .mapUnitDepth = 51200,
		.authored =
		{
			{ 24250,  40900,  0 },	// p0
			{ 39200,   8150,  6 },	// p1
			{ 25150,  41000,  0 },	// p2
			{ 37900,   8250,  6 },	// p3
			{ 24650,  42250,  0 },	// p4
			{ 38400,   9400,  6 },	// p5
		},
		.extra =
		{
			{ 25600,  41900,  0 },	// p6: moved 509 from the rule
			{ 37500,   9100,  6 },	// p7: moved 710 from the rule
			{ 25900,  40100,  0 },	// p8: moved 1486 from the rule
			{ 37300,  10300,  6 },	// p9: moved 1644 from the rule
			{ 25900,  42750,  0 },	// p10: rule
			{ 38500,  10600,  6 },	// p11: moved 1432 from the rule
		},
	},
};

const int kNumStartSlotTableEntries = (int) (sizeof(kStartSlotTable) / sizeof(kStartSlotTable[0]));
