//
// startslots.h
//
// Start slots for players beyond the ones a playfield authors. Every shipped playfield has six
// MyStartCoord items per slot set; StartSlotTable.c (generated by tools/gen_start_slots.py)
// holds six more per set for each shipped map, keyed by the authored slots.
//

#pragma once

#define	START_SLOT_TABLE_AUTHORED	6			// authored slots per set on the shipped maps (players 0-5)
#define	START_SLOT_TABLE_EXTRA		6			// table slots per set (players 6-11)

typedef enum
{
	START_SLOT_SET_RACE,						// race grid
	START_SLOT_SET_BATTLE,						// Tag and Survival: arena items without parm[3] bit 0
	START_SLOT_SET_CTF,							// Capture the Flag: parm[3] bit 0; even players red, odd green
} StartSlotSet;

typedef struct
{
	int		x, z;								// world units, as gPlayerInfo[].startX/startZ
	int		rot16;								// heading in 1/16 turns, as MyStartCoord parm[1]
} StartSlot;

typedef struct
{
	const char*		map;						// playfield name (for people reading the table)
	StartSlotSet	set;
	int				mapUnitWidth, mapUnitDepth;	// gTerrainUnitWidth/Depth
	StartSlot		authored[START_SLOT_TABLE_AUTHORED];	// players 0-5 exactly as authored: the key
	StartSlot		extra[START_SLOT_TABLE_EXTRA];			// players 6-11
} StartSlotTableEntry;

extern const StartSlotTableEntry	kStartSlotTable[];
extern const int					kNumStartSlotTableEntries;
