//
// startslots.h
//
// Start slots for players beyond the ones a playfield authors. Every shipped playfield has six
// MyStartCoord items per slot set; StartSlotTable.c (generated by tools/gen_start_slots.py)
// holds six more per set for each shipped map, keyed by the authored slots. StartSlots.c gives
// every player a slot: authored, else from the table, else from a procedural rule. It depends
// only on map data, so every network peer derives the same slots.
//

#pragma once

#include <stdbool.h>
#include "structs.h"							// TerrainItemEntryType

#define	START_SLOT_TABLE_AUTHORED	6			// authored slots per set on the shipped maps (players 0-5)
#define	START_SLOT_TABLE_EXTRA		6			// table slots per set (players 6-11)
#define	START_SLOTS_MAX				32			// most slots StartSlots_Place fills (>= MAX_PLAYERS)

typedef enum
{
	START_SLOT_SET_RACE,						// race grid
	START_SLOT_SET_BATTLE,						// Tag and Survival: arena items without parm[3] bit 0
	START_SLOT_SET_CTF,							// Capture the Flag: parm[3] bit 0; even players red, odd green
} StartSlotSet;

typedef struct
{
	int		x, z;								// world units, as gPlayerInfo[].startX/startZ
	int		rot16;								// heading in 1/16 turns, as MyStartCoord parm[1]
} StartSlot;

typedef struct
{
	const char*		map;						// playfield name (for people reading the table)
	StartSlotSet	set;
	int				mapUnitWidth, mapUnitDepth;	// gTerrainUnitWidth/Depth
	StartSlot		authored[START_SLOT_TABLE_AUTHORED];	// players 0-5 exactly as authored: the key
	StartSlot		extra[START_SLOT_TABLE_EXTRA];			// players 6-11
} StartSlotTableEntry;

extern const StartSlotTableEntry	kStartSlotTable[];
extern const int					kNumStartSlotTableEntries;

typedef struct
{
	int		x, z;								// gPlayerInfo[].startX/startZ
	float	rotY;								// gPlayerInfo[].startRotY
} StartSlotPose;

float StartSlot_RotY(int rot16);
int StartSlots_CountAuthored(const bool authored[], int numSlots);
const StartSlotTableEntry* StartSlots_Fill(StartSlotSet set, int mapUnitWidth, int mapUnitDepth,
										const StartSlot items[], const bool authored[], int numSlots,
										StartSlotPose poses[]);
void StartSlots_KeepHumansAtBack(StartSlotPose poses[], const bool isComputer[], int numPlayers, int authoredCount,
								int gridRot16);
StartSlotSet StartSlots_SetForGameMode(int gameMode);
int StartSlots_Place(const TerrainItemEntryType itemList[], long numItems, int gameMode,
					int mapUnitWidth, int mapUnitDepth, const bool isComputer[], int numPlayers,
					int numSlots, StartSlotPose poses[]);
