if(NOT MODE STREQUAL "CHECK" AND NOT MODE STREQUAL "RECORD")
    message(FATAL_ERROR "MODE must be CHECK or RECORD")
endif()
file(REAL_PATH "${NDK_DIR}/build/cmake/android.toolchain.cmake" toolchain)
file(SHA256 "${NDK_DIR}/source.properties" revision_digest)
if(WIN32)
    string(TOLOWER "${toolchain}" toolchain)
endif()
# Both repository wrappers configure with Ninja, including when switching shells.
set(identity "${toolchain}\n${revision_digest}\nNinja\n")
set(stamp "${BUILD_DIR}/cmr-ndk.stamp")

if(MODE STREQUAL "RECORD")
    file(WRITE "${stamp}" "${identity}")
elseif(EXISTS "${BUILD_DIR}/CMakeCache.txt")
    set(previous "")
    if(EXISTS "${stamp}")
        file(READ "${stamp}" previous)
    endif()
    if(NOT previous STREQUAL identity)
        message(STATUS "Removing stale CMake build tree for a different or unknown NDK: ${BUILD_DIR}")
        file(REMOVE_RECURSE "${BUILD_DIR}")
    endif()
endif()
