if(NOT IS_DIRECTORY "${ASSETS_DIR}/Data")
    message(FATAL_ERROR "ASSETS_DIR must contain the staged Data directory")
endif()

file(GLOB_RECURSE asset_files LIST_DIRECTORIES false RELATIVE "${ASSETS_DIR}" "${ASSETS_DIR}/Data/*")
list(SORT asset_files)
set(manifest "")
set(content_manifest "")
foreach(asset IN LISTS asset_files)
    if(asset STREQUAL "Data/files.txt" OR asset STREQUAL "Data/content.sha256")
        continue()
    endif()
    if(asset MATCHES "[\r\n]")
        message(FATAL_ERROR "Asset paths cannot contain line breaks")
    endif()
    file(SHA256 "${ASSETS_DIR}/${asset}" digest)
    string(APPEND manifest "${asset}\n")
    string(APPEND content_manifest "${digest}  ${asset}\n")
endforeach()
string(SHA256 content_id "${content_manifest}")
file(WRITE "${ASSETS_DIR}/Data/files.txt" "${manifest}")
file(WRITE "${ASSETS_DIR}/Data/content.sha256" "${content_id}")
